sudo: true

language: java

jdk:
  - openjdk12

addons:
  apt:
    update: true

install:
  - sudo apt-get install -y -qq python3 spim
  - git clone https://github.com/decaf-lang/decaf-2019-TestCases TestCases

script:
  - gradle --version
  - gradle clean && gradle build
  - java --version
  - java -jar --enable-preview build/libs/decaf.jar -h
  - cd TestCases
  - python3 testAll.py PA1-A
  - python3 testAll.py PA1-B
  - python3 testAll.py PA2
  - python3 testAll.py PA3
  - python3 testAll.py PA4
  - python3 testAll.py PA5
